// Mock data for demonstration purposes

export const mockMedications = [
  {
    id: '1',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily',
    schedule: ['09:00'],
    startDate: new Date('2024-01-15'),
    endDate: null,
    prescribedBy: 'Dr. Sarah Johnson',
    purpose: 'Blood pressure management',
    refillsRemaining: 3,
    nextRefillDate: new Date('2025-12-01'),
    status: 'active',
    sideEffects: ['Dizziness', 'Dry cough'],
    instructions: 'Take with food in the morning',
  },
  {
    id: '2',
    name: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    schedule: ['08:00', '20:00'],
    startDate: new Date('2024-03-01'),
    endDate: null,
    prescribedBy: 'Dr. Michael Chen',
    purpose: 'Type 2 diabetes management',
    refillsRemaining: 2,
    nextRefillDate: new Date('2025-11-20'),
    status: 'active',
    sideEffects: ['Nausea', 'Stomach upset'],
    instructions: 'Take with meals',
  },
  {
    id: '3',
    name: 'Atorvastatin',
    dosage: '20mg',
    frequency: 'Once daily',
    schedule: ['21:00'],
    startDate: new Date('2024-02-10'),
    endDate: null,
    prescribedBy: 'Dr. Sarah Johnson',
    purpose: 'Cholesterol management',
    refillsRemaining: 1,
    nextRefillDate: new Date('2025-11-15'),
    status: 'active',
    sideEffects: ['Muscle pain', 'Headache'],
    instructions: 'Take in the evening',
  },
];

export const mockReminders = [
  {
    id: 'r1',
    medicationId: '1',
    scheduledTime: new Date(new Date().setHours(9, 0, 0, 0)),
    status: 'pending',
    takenAt: null,
    snoozedUntil: null,
    medicationName: 'Lisinopril',
    dosage: '10mg',
  },
  {
    id: 'r2',
    medicationId: '2',
    scheduledTime: new Date(new Date().setHours(8, 0, 0, 0)),
    status: 'taken',
    takenAt: new Date(new Date().setHours(8, 15, 0, 0)),
    snoozedUntil: null,
    medicationName: 'Metformin',
    dosage: '500mg',
  },
];

export const mockPrescriptions = [
  {
    id: 'p1',
    medicationId: '1',
    prescribedDate: new Date('2024-01-15'),
    expiryDate: new Date('2026-01-15'),
    initialRefills: 5,
    refillsUsed: 2,
    prescribingDoctor: 'Dr. Sarah Johnson',
    pharmacy: 'CVS Pharmacy',
    prescriptionNumber: 'RX123456',
    status: 'active',
    fileUrl: null,
  },
  {
    id: 'p2',
    medicationId: '3',
    prescribedDate: new Date('2024-02-10'),
    expiryDate: new Date('2025-11-20'),
    initialRefills: 3,
    refillsUsed: 2,
    prescribingDoctor: 'Dr. Sarah Johnson',
    pharmacy: 'Walgreens',
    prescriptionNumber: 'RX789012',
    status: 'active',
    fileUrl: null,
  },
];

export const mockUserProfile = {
  id: 'u1',
  name: 'John Doe',
  dateOfBirth: new Date('1975-06-15'),
  allergies: ['Penicillin', 'Sulfa drugs'],
  conditions: ['Hypertension', 'Type 2 Diabetes', 'High Cholesterol'],
  emergencyContact: 'Jane Doe',
  emergencyPhone: '555-0123',
  doctors: [
    {
      id: 'd1',
      name: 'Dr. Sarah Johnson',
      specialty: 'Cardiology',
      phone: '555-0100',
      email: 'sjohnson@hospital.com',
      address: '123 Medical Plaza, Suite 200',
    },
    {
      id: 'd2',
      name: 'Dr. Michael Chen',
      specialty: 'Endocrinology',
      phone: '555-0200',
      email: 'mchen@hospital.com',
      address: '456 Health Center Dr',
    },
  ],
};

export const mockAdherenceRecords = [
  { id: 'a1', medicationId: '1', date: new Date('2025-11-01'), taken: true, missedReason: null },
  { id: 'a2', medicationId: '1', date: new Date('2025-11-02'), taken: true, missedReason: null },
  { id: 'a3', medicationId: '1', date: new Date('2025-11-03'), taken: false, missedReason: 'Forgot' },
  { id: 'a4', medicationId: '2', date: new Date('2025-11-01'), taken: true, missedReason: null },
  { id: 'a5', medicationId: '2', date: new Date('2025-11-02'), taken: true, missedReason: null },
];
